### ISSUE TITLE
STAR not listening to --localcores

### ISSUE THREAD

**Issue by kehey** [10XGenomics/cellranger#48] opened 2019-11-21 12:36 UTC
It seems that STAR will always run on 4 cores, also when `--localcores` is set at two, which should be the maximal number of cores used according to the parameter description.

Linked to https://github.com/10XGenomics/cellranger/issues/25 but then from the perspective of making number of cores listen to `--localcores` instead of using all available cores

**Comment by adam-azarchs** [comment] 2020-01-14 20:01
First of all keep in mind that if you are running a released tarball you should contact [10X's support team](mailto:support@10xgenomics.com) for assistance.  They're very good at what they do, and will generally respond much faster than what you'll get on github issues.

The problem is in the [stage code for align_reads](https://github.com/10XGenomics/cellranger/blob/3.0.2/mro/stages/counter/align_reads/__init__.py#L66) where it is ignoring the actual thread count assigned by `mrp`.  It should be using `martian.get_threads_allocation()` (or, prior to [martian](https://github.com/martian-lang/martian) v3.1.0, `args.__threads`).  This will be fixed in a future release of cellranger.

**Closed** 2020-01-14 20:20 UTC
