### ISSUE TITLE
cell ranger reanalyze makes loupe file with "Invalid File Format"

### ISSUE THREAD

**Issue by jeffpkamp** [10XGenomics/cellranger#203] opened 2023-02-13 15:40 UTC
I am feeding an h5 file into cellranger reanalyze.   The program completes without any errors and I don't see any errors in the logs, but when I try to open the cloupe file made by it I get the error message:

 "Loupeserver encountered an error: invalid file format"

can you advise me on troubleshooting the problem?

**Comment by evolvedmicrobe** [comment] 2023-02-16 22:44
This usually indicates that reanalyze was run with an input file that wasn't produced by Cell Ranger, was your input matrix modified after running Cell Ranger?

**Comment by jeffpkamp** [comment] 2023-02-16 23:45
Yes, we have normalized several sets or visium data and I am using `cellranger reanalyzed` to make the loupe files from a modified h5 file.  I'm not asking for you to support this, just hoping you could point me toward where I might find the problem, since the error message is not informative and I didn't see any problems in the logs.

**Comment by jeffpkamp** [comment] 2023-02-17 20:36
Okay, so I tested reanalyze out with an h5 file that I haven't modified, and I am getting the same error when trying to open the loupe file.

I am running reanalyzed like this:

```cellranger reanalyze --id re_test --matrix "./corrected_A7384/SpaceRanger/19938X4/outs/filtered_feature_bc_matrix.h5"```

**Comment by evolvedmicrobe** [comment] 2023-02-17 20:53
The issue is that `spaceranger` data is not supported in `cellranger reanalyze`, this is an interesting use case though, and there may be some features coming out soon (not committed to yet), that will enable you to do this.

**Comment by jeffpkamp** [comment] 2023-02-17 21:35
I found the problem.  I was running cellranger 5.0.  I ran it with the newest cellranger available at 10x's website, 7.1 and it worked with both the control and modified data.

**Closed** 2023-11-06 18:22 UTC
